print("                                                                             ")
print("       __        __   _______        ___        ___________      _                                      ")
print("       \ \  __  / /   |  ____|      / _ \      |____   ____|    |  \                          ")
print("        \ \/  \/ /    | |_         / / \ \          | |         |   \                    ")
print("         \__/\__/     |  _|       / /___\ \         | |         | _  /                        ")
print("                      | |____    / /     \ \        | |         | \                     ")
print("                      |______|  /_/       \_\       |_|         |  \                ")
print("                                                                |   \         ")
print("                                                                             ")


print("~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~")
print("'                                                                   '")
print("'      Thanks For Using Our Weather Python Program - Byy !!!!!      '")
print("'                      CREATED BY - Vinit Vijal                     '")
print("'                                                                   '")
print("~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~")
print("                                                                             ")
print("                                                                             ")
print("                                                                             ")
print("                                                                             ")
print("                                                                             ")
